#!/bin/bash

function extractPixelSizeFromString {
  
}
#Ask user if he is in the directory to operate program
while true; do
  read -p "Are you in the directory with pictures to separate (y/n)?: " useCurrentDirectory
  if [ $useCurrentDirectory == "y" ] || [ $useCurrentDirectory == "n" ]; then
    break
  fi
  echo "invalid input"
done

#Build directory path
if [ $useCurrentDirectory == "n" ]; then
  while true; do
    read -p "Enter the path to the directory to operate program: " directoryLocation
    #if prompted directory location is valid, continue
    if [ -d $directoryLocation ]; then 
      break
    fi
    echo "invalid path"
  done
else
  directoryLocation="$(PWD)"
fi


#criteria to separate pictures
while true; do 
  read -p "`echo -e 'Separate pictures depending on which criteria? \n
  e -> EXIF (picture metadata - vertical or horizontal) \n
  s -> size \n
  '`" criteria
  if [ $criteria == "e" ] || [ $criteria == "s" ]; then
    break
  fi
  echo "invalid input"
done

#if criteria = size
if [ $criteria == "s" ]; then
  #ask if use default size file 
  while true; do
    read -p "use default picture sizes in defaultSize.txt? (y/n)" useDefaultSizeFile
    if [ $useDefaultSizeFile == "y" ] || [ $useDefaultSizeFile == "n" ]; then
      break
    fi
    echo "invalid input"
  done

  #if use default size
  if [ $useDefaultSizeFile == "y" ]; then 
    chmod +x rr.sh
    sizes=$(./rr.sh ./defaultSize.txt)
    echo $sizes
  fi
fi

#separate pictures




echo "done"

